project:
    type: website
    output-dir: docs
website:
    navbar:
        title: "東京地図"
        tools:
          - icon: github
            href: https://www.github.com/tokyochizu
    sidebar:
        style: "docked"
        contents:
          - href: layout.qmd
            text: Layout
          - href: zoning.qmd
            text: Zoning
          - href: map3.qmd
            text: Map 3
          - href: map1.qmd
            text: Disaster
            
format:
    html:
        theme: superhero
        toc: true